# Generated by Django 5.0.3 on 2024-03-08 11:16

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_status_profile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('articlemanager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to='blog.profile'),
        ),
    ]
