# Generated by Django 5.0.3 on 2024-03-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_managers_post_content_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
