# Generated by Django 5.0.3 on 2024-03-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_image',
            field=models.ImageField(blank=True, default='img/placeholder.svg', null=True, upload_to='author_images'),
        ),
    ]
